apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: voting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: aseefahmed/postgres
        name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
