apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
  namespace: voting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: aseefahmed/app_result
        name: result
