apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
  namespace: votings
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: aseefahmed/app_vote
        name: vote
