apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: voting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: aseefahmed/app_worker
        name: worker
